### ISSUE TITLE
Run/Compile Issue

### ISSUE THREAD

**Issue by bannsec** [ehrmann/pcap-endianness-converter#1] opened 2017-06-24 17:28 UTC
Heads up. Your tool doesn't run or compile correctly on my Ubutnu.

```
$ java -jar one-jar-ant-task-0.97.jar 
no main manifest attribute, in one-jar-ant-task-0.97.jar
$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**Comment by ehrmann** [comment] 2017-06-25 05:55
I was able to reproduce a build issue.  the `lib` directory is missing in git. It was supposed to have junit, but it's not part of the build, so somehow it never made it in. This is fixed.

I think your running issue is that you're running the wrong file. If the build works now, try `java -jar pcap-endianness-converter.jar`

**Comment by bannsec** [comment] 2017-06-25 17:17
Ah. Yeah, need the build to get to that file. Can confirm I was able to build it.

Any thoughts to either placing the pre-compiled jar file the repo? Or creating a docker image?

Also, thoughts to adding tcpdump format endianness convert to this tool?

**Comment by ehrmann** [comment] 2017-06-25 19:39
> Any thoughts to either placing the pre-compiled jar file the repo?

There already is: https://github.com/ehrmann/pcap-endianness-converter/releases

> Or creating a docker image?

I tend to see this as an abuse of docker. It's a little absurd to distribute an *OS image* for such a simple tool.

> Also, thoughts to adding tcpdump format endianness convert to this tool?

Do you mean also support the tcpdump format? As far as I can tell, (see -w in the [man page](http://www.tcpdump.org/manpages/tcpdump.1.html)), tcpdump uses the pcap format.

**Comment by bannsec** [comment] 2017-06-26 14:56
Hmm.. so on point one, I git clone'd which caused me to only find the jar `one-jar-ant-task-0.97.jar` which was apparently not the correct one. Haven't had time to check releases.

Up to you on the docker thing. For what it's worth, Ubuntu has a tiny footprint by default from their Docker image, so it would like be a small image. Plus i believe Alpine is generally used if size is a concern.

And no, tcpdump has their own format apparently. Attaching the example dump.

[file01.zip](https://github.com/ehrmann/pcap-endianness-converter/files/1102532/file01.zip)

**Comment by ehrmann** [comment] 2017-06-27 03:56
What tool generated that file? I read around, and pcapng exists, but that looks like a regular pcap file.  If you look at the first four bytes, they're `a1 b2 c3 d4`. That's the magic for a big-endian pcap. What's strange is that the next four bytes are supposed to indicate the major and minor version. They do, and they indicate the correct version, but they're little endian. So I'm wondering if the tool you're using has a bug.

**Comment by bannsec** [comment] 2017-06-27 04:02
Dunno what made it. It was a part of a ctf that just ran a week or so ago.

**Comment by ehrmann** [comment] 2017-06-27 13:12
Wireshark can't seem to open it, either, and Wireshark supports pcapng. I think your file is a buggy or proprietary pcap file.

**Comment by ehrmann** [comment] 2017-06-30 02:50
Any more info that might point me in the right direction?

**Comment by bannsec** [comment] 2017-06-30 12:32
Sorry. I have no idea what created. My assumption was a version of tcpdump on a big endian OS (maybe ARM?).

**Comment by ehrmann** [comment] 2017-06-30 13:22
Could you try opening it in wireshark? I wasn't able to, so I think this is an issue with whatever captured it.

**Comment by bannsec** [comment] 2017-06-30 13:22
Yeah I couldn't either

**Comment by ehrmann** [comment] 2017-07-01 01:50
I don't think this is an issue with an unsupported format, so I'm closing the issue. If you're ever interested in pcapng, let me know.

**Closed as completed by ehrmann** 2017-07-01 01:50 UTC
